# This file was generated by GoReleaser. DO NOT EDIT.
cask "choam" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e53b5f356bd7954f00c68e2d132be61e60124ec273009a4d7bfd73e4c16a0090"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "236edf3e2d3a993f1acf6c0b1d64cca3b4c9aea3bb78a182ee87e43c8dd31856"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "abc32602185d18295112629dc64fa14db0f75ec5d4d813b874866950753aa54a"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "0c6276ee9de881117324cf052c4e5afc5a5b37130dd30d81b89a2815c30fca36"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_linux_arm64.zip"
    end
  end

  name "choam"
  desc "Track updates for melange build specification files"
  homepage "https://just.breathe.io/project/choam/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choam"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choam"]
    end
  end

  # No zap stanza required

end
