# This file was generated by GoReleaser. DO NOT EDIT.
cask "choam" do
  name "choam"
  desc "Track updates for melange build specification files"
  homepage "https://just.breathe.io/project/choam/"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choam"

  on_macos do
    on_intel do
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_darwin_amd64.zip"
      sha256 "4197e4e0e0e58ba5c2025aa40063172fea40057d6911a09682cfaf97a7b13494"
    end
    on_arm do
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_darwin_arm64.zip"
      sha256 "a21e785f4117f4ae539c4a7387f1ee717c6fac308dafd6e5f7a26580b65f86f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_linux_amd64.zip"
      sha256 "bc50a7ea3b6982327b740dc2ca3bbe57496bacc4171389d1a473a150eb8a5ea0"
    end
    on_arm do
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_linux_arm64.zip"
      sha256 "f34851fa3ff9e2440c4655ebe3512534b721494734e4c29329d1bce7dddf38c9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choam"]
    end
  end

  # No zap stanza required
end
