# This file was generated by GoReleaser. DO NOT EDIT.
cask "choam" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ff0be1cf897883a405b06d9259c689f4b0447174d3fedade6bf26aacbf674b5b"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "b683d074c3bdccf8946aa262a9d26aa75481ae37cf6a34915b286f735a956727"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "4590a8e4bd2e64fa4d742565b7684765a6e58c5339d9717c26fc5c0fe5e17720"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "269d93864883618944a397b899c82f688dfd0d990c941d25420867fb7102779b"
      url "https://github.com/isometry/choam/releases/download/v#{version}/choam_#{version}_linux_arm64.zip"
    end
  end

  name "choam"
  desc "Track updates for melange build specification files"
  homepage "https://just.breathe.io/project/choam/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choam"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choam"]
    end
  end

  # No zap stanza required

end
