# This file was generated by GoReleaser. DO NOT EDIT.
cask "yaketty" do
  name "yaketty"
  desc "Orchestrated conversations between AI personas using Ollama"
  homepage "https://just.breathe.io/project/yaketty/"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yaketty"

  on_macos do
    on_intel do
      url "https://github.com/isometry/yaketty/releases/download/v#{version}/yaketty_#{version}_darwin_amd64.zip"
      sha256 "b2d9c11c802729c404620cdbc3b0301b89520fcb4b632e5ddc5b1549ec0482fb"
    end
    on_arm do
      url "https://github.com/isometry/yaketty/releases/download/v#{version}/yaketty_#{version}_darwin_arm64.zip"
      sha256 "c2845fb7d15bd4fab49b3ba5e2e2f42b2a9e5547b6be6e32b1660beba4674da2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/isometry/yaketty/releases/download/v#{version}/yaketty_#{version}_linux_amd64.zip"
      sha256 "e868d82029dfa650dbbe2702cf4ccd1be117bdc1facb3a6e463b446ecd6051f3"
    end
    on_arm do
      url "https://github.com/isometry/yaketty/releases/download/v#{version}/yaketty_#{version}_linux_arm64.zip"
      sha256 "5be506f7ba1fa2a3818207c6a2f01dd6c7e950e61e4f74f00e85187bace4af40"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yaketty"]
    end
  end

  # No zap stanza required
end
