# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitrat < Formula
  desc "Lightning-fast, multi-algorithm file checksums"
  homepage "https://just.breathe.io/project/bitrat/"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/isometry/bitrat/releases/download/v0.1.0/bitrat_0.1.0_darwin_amd64.zip"
      sha256 "52df6cb3cdd294896f5ee8a84d9b956eb16f19c0a4213a654bf9763dcdf9a931"

      def install
        bin.install "bitrat"
      end
    end
    on_arm do
      url "https://github.com/isometry/bitrat/releases/download/v0.1.0/bitrat_0.1.0_darwin_arm64.zip"
      sha256 "f9255d047f5a3765931cabab05bb72051e3e0bb53a2c1d56de18292518c2dff7"

      def install
        bin.install "bitrat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/bitrat/releases/download/v0.1.0/bitrat_0.1.0_linux_amd64.zip"
        sha256 "18231d7364ea3fc228a15f73b8185f5f92ed713d40a27c9b64814821f54dd1ed"

        def install
          bin.install "bitrat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/bitrat/releases/download/v0.1.0/bitrat_0.1.0_linux_arm64.zip"
        sha256 "5e92d4c085429035df2cbba9a83a07a6e54009fde6c6335a05e79d6c3c6f8bfc"

        def install
          bin.install "bitrat"
        end
      end
    end
  end

  test do
    system "#{bin}/bitrat --help"
  end
end
