# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitrat < Formula
  desc "Lightning-fast, multi-algorithm file checksums"
  homepage "https://just.breathe.io/project/bitrat/"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/bitrat/releases/download/v0.2.1/bitrat_0.2.1_darwin_amd64.zip"
      sha256 "146e8729b97a7db051a4f5da770c935fc4eecdb4082b8c80bcae50dc5f4c4a4a"

      define_method(:install) do
        bin.install "bitrat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/bitrat/releases/download/v0.2.1/bitrat_0.2.1_darwin_arm64.zip"
      sha256 "8a4a5081a0b098dec3c53f49e45fe48ee3c3a1c9b66af4f297c13f7ac91b72c1"

      define_method(:install) do
        bin.install "bitrat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/bitrat/releases/download/v0.2.1/bitrat_0.2.1_linux_amd64.zip"
      sha256 "2183306742c08c586b495965c306020fa10233ddcd6cd117f3c4fef8aa5e090c"
      define_method(:install) do
        bin.install "bitrat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/bitrat/releases/download/v0.2.1/bitrat_0.2.1_linux_arm64.zip"
      sha256 "e39db23a599de0e4a73d4aa768ec0f27ce8000484709dc35c366a00f3e68c190"
      define_method(:install) do
        bin.install "bitrat"
      end
    end
  end

  test do
    system "#{bin}/bitrat --help"
  end
end
