# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitrat < Formula
  desc "Lightning-fast, multi-algorithm file checksums"
  homepage "https://just.breathe.io/project/bitrat/"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/bitrat/releases/download/v0.1.2/bitrat_0.1.2_darwin_amd64.zip"
      sha256 "cffc761343db6d3b0027bfc0a2e01d6c1b485b34d386ed3b8d613118e062b847"

      def install
        bin.install "bitrat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/bitrat/releases/download/v0.1.2/bitrat_0.1.2_darwin_arm64.zip"
      sha256 "81fa2566d4b094253ecb706c758215b7c077f78778e78805d03b822704f6eed8"

      def install
        bin.install "bitrat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/bitrat/releases/download/v0.1.2/bitrat_0.1.2_linux_amd64.zip"
      sha256 "bc57ce3cffcd0c6f560f1ae30b30bbdc5c9fb8ace132da89c7a95d2a7e26739e"
      def install
        bin.install "bitrat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/bitrat/releases/download/v0.1.2/bitrat_0.1.2_linux_arm64.zip"
      sha256 "a0aef8584519a400cf8abdfb508e26f248ea0f81bccfa0896af507dc83000597"
      def install
        bin.install "bitrat"
      end
    end
  end

  test do
    system "#{bin}/bitrat --help"
  end
end
