# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCredentialEnv < Formula
  desc "Environment-driven Docker credential helper"
  homepage "https://just.breathe.io/project/docker-credential-env/"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.5.0/docker-credential-env_1.5.0_darwin_amd64.zip"
      sha256 "333a8624244f08c4d9ec2fcc85426e104e8bae3c8cbcc089a98568df8c312f4a"

      def install
        bin.install "docker-credential-env"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.5.0/docker-credential-env_1.5.0_darwin_arm64.zip"
      sha256 "45c920a2f359c0b2286c1427b6cb25d5f55416797079a281d0647ae014edaf53"

      def install
        bin.install "docker-credential-env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.5.0/docker-credential-env_1.5.0_linux_amd64.zip"
      sha256 "72f8ed9cca742a8d3aeacf834e78f884d76b60377e8bfd3d48f477898f39d1f1"
      def install
        bin.install "docker-credential-env"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.5.0/docker-credential-env_1.5.0_linux_arm64.zip"
      sha256 "5c4767b1dadde01191be3b8a0c7411475dbfa42e24030e1e95c5bfbc3ab87aff"
      def install
        bin.install "docker-credential-env"
      end
    end
  end

  test do
    system "#{bin}/docker-credential-env --version"
  end
end
