# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCredentialEnv < Formula
  desc "Environment-driven Docker credential helper"
  homepage "https://just.breathe.io/project/docker-credential-env/"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.6.0/docker-credential-env_1.6.0_darwin_amd64.zip"
      sha256 "8a7b0184175705e80dc462354766877604d6c74ff9f8043b37eb774c0b7c083c"

      def install
        bin.install "docker-credential-env"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.6.0/docker-credential-env_1.6.0_darwin_arm64.zip"
      sha256 "5db735a24022fb7765196f6d8e361d66e4fb65ef30443b8c733420e95d4294d7"

      def install
        bin.install "docker-credential-env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.6.0/docker-credential-env_1.6.0_linux_amd64.zip"
      sha256 "69f2025b2e4d23dc103db37b3a92cc979e15ff15c5c80c346ebbf700b65605fb"
      def install
        bin.install "docker-credential-env"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/docker-credential-env/releases/download/v1.6.0/docker-credential-env_1.6.0_linux_arm64.zip"
      sha256 "dfdf93f47a0f5f83a0bbb6822554daee0e763a9a072079f21b4ab894fe49970f"
      def install
        bin.install "docker-credential-env"
      end
    end
  end

  test do
    system "#{bin}/docker-credential-env --version"
  end
end
