# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghait < Formula
  desc "Easily generate GitHub App Installation Tokens"
  homepage "https://just.breathe.io/project/ghait/"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/ghait/releases/download/v0.5.0/ghait_0.5.0_darwin_amd64.zip"
      sha256 "74e225e16ae08affbf463e73e3a3f2568f1f3bb29ecc24a6315c3d9d9c1d7ec1"

      def install
        bin.install "ghait"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/ghait/releases/download/v0.5.0/ghait_0.5.0_darwin_arm64.zip"
      sha256 "320c3d34cd4294705b1d48afb7c9b7d3424c3b126b62cb3d37d3aa97e50963f1"

      def install
        bin.install "ghait"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/ghait/releases/download/v0.5.0/ghait_0.5.0_linux_amd64.zip"
      sha256 "f595891f8f0e2b93bf2b3a47e5da59dd0214629e934b2c9ce35c1b4f8be1947f"
      def install
        bin.install "ghait"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/ghait/releases/download/v0.5.0/ghait_0.5.0_linux_arm64.zip"
      sha256 "77465ab1970749da917a468fe2dc929911363d9a6d2e8ab8746f5d5752f1d150"
      def install
        bin.install "ghait"
      end
    end
  end

  test do
    system "#{bin}/ghait --help"
  end
end
