# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghait < Formula
  desc "Easily generate GitHub App Installation Tokens"
  homepage "https://just.breathe.io/project/ghait/"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/ghait/releases/download/v0.2.1/ghait_0.2.1_darwin_amd64.zip"
      sha256 "7e869abb0ca89716fd042ab6818f5d8b2246a080ab9edd20e2522970c3373a7f"

      def install
        bin.install "ghait"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/ghait/releases/download/v0.2.1/ghait_0.2.1_darwin_arm64.zip"
      sha256 "257877dab4d3adfd6b16a63dff93ba73c4d8eec8175f745c740edb175bf2adf7"

      def install
        bin.install "ghait"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/ghait/releases/download/v0.2.1/ghait_0.2.1_linux_amd64.zip"
        sha256 "1db721d2c236157ec0ff2afefd7042308610b5738a3d517b264658995b945acf"

        def install
          bin.install "ghait"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/ghait/releases/download/v0.2.1/ghait_0.2.1_linux_arm64.zip"
        sha256 "a1d3de4c750b56d20f88086875566200781ef536ae7b8bd810db93243bf975ba"

        def install
          bin.install "ghait"
        end
      end
    end
  end

  test do
    system "#{bin}/ghait --help"
  end
end
