# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghat < Formula
  desc "Easily generate GitHub App Installation Tokens"
  homepage "https://just.breathe.io/project/ghat/"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/isometry/ghat/releases/download/v0.1.0/ghat_0.1.0_darwin_amd64.zip"
      sha256 "0ea384c444af566f6a0a2fb0386da900757982c0793ce707f934909a44e9c76f"

      def install
        bin.install "ghat"
      end
    end
    on_arm do
      url "https://github.com/isometry/ghat/releases/download/v0.1.0/ghat_0.1.0_darwin_arm64.zip"
      sha256 "5a9f10c69ceac054f70b8321be4ac17f33602d3b12a083932e36caca16b7868a"

      def install
        bin.install "ghat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/ghat/releases/download/v0.1.0/ghat_0.1.0_linux_amd64.zip"
        sha256 "9a739937ba04a2d1cd3e85f013ed7e89da5b8a399b2403c49d2036a0ae319110"

        def install
          bin.install "ghat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/ghat/releases/download/v0.1.0/ghat_0.1.0_linux_arm64.zip"
        sha256 "22675e57d774c7879c5f95ef3ab7cacbd306321bab4f42d2c5b46a7b62257659"

        def install
          bin.install "ghat"
        end
      end
    end
  end

  test do
    system "#{bin}/ghat --help"
  end
end
