# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghup < Formula
  desc "A GitHub API client for managing tags and repository content from third-party automation systems"
  homepage "https://just.breathe.io/project/ghup/"
  version "0.14.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.14.0/ghup_0.14.0_darwin_amd64.zip"
      sha256 "70848a2f9d783e4696e2e861f96876385c2ced95a7afe588874893492d76bf7d"

      def install
        bin.install "ghup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.14.0/ghup_0.14.0_darwin_arm64.zip"
      sha256 "bc11cd3f32da837025c02b7c1d10a719ee498855140efe2bb9342ee8b9829f61"

      def install
        bin.install "ghup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.14.0/ghup_0.14.0_linux_amd64.zip"
      sha256 "e9b87e45dc22147008420568e158ef54a00548cd461c484eebbcbc07b12acff0"
      def install
        bin.install "ghup"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.14.0/ghup_0.14.0_linux_arm.zip"
      sha256 "a9b7ee9a934d4aa33020bb7977c124eda2bf5dd56a16f69478a117648e4b8f24"
      def install
        bin.install "ghup"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.14.0/ghup_0.14.0_linux_arm64.zip"
      sha256 "c4a3bf9e7aea05a8665bdbdb2ffc60f1d5feb7932dff7fcec9b95b765f82d060"
      def install
        bin.install "ghup"
      end
    end
  end

  test do
    system "#{bin}/ghup --help"
  end
end
