# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghup < Formula
  desc "A GitHub API client for managing tags and repository content from third-party automation systems"
  homepage "https://just.breathe.io/project/ghup/"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.15.0/ghup_0.15.0_darwin_amd64.zip"
      sha256 "985f6935442a8fbc4cc1292fc0263898e19aacd598e9ec319995da607b12ba56"

      def install
        bin.install "ghup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.15.0/ghup_0.15.0_darwin_arm64.zip"
      sha256 "730130ac50110178feace324c631a2b35c91172af6b575b766b487862148aedc"

      def install
        bin.install "ghup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.15.0/ghup_0.15.0_linux_amd64.zip"
      sha256 "032ac7befa293a03b14c0b0bfa25e6c15bdd0774d312eaf358e42dbc9e4746f1"
      def install
        bin.install "ghup"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.15.0/ghup_0.15.0_linux_arm.zip"
      sha256 "ca87f8ae54d1bdf4369e80c42e1fdfa6a6f9e7ad6ed8d96da1ec567d6ec7bdbb"
      def install
        bin.install "ghup"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/ghup/releases/download/v0.15.0/ghup_0.15.0_linux_arm64.zip"
      sha256 "f62bc6e43db5f5ffeeb9eda85905d8a5f93e2badc538dacd4d6686ef83e480b0"
      def install
        bin.install "ghup"
      end
    end
  end

  test do
    system "#{bin}/ghup --help"
  end
end
