# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GiteaMirror < Formula
  desc "Manage Gitea mirror lifecycle"
  homepage "https://just.breathe.io/project/gitea-mirror/"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nexthink-oss/gitea-mirror/releases/download/v0.6.0/gitea-mirror_0.6.0_darwin_amd64.zip"
      sha256 "fde94bce8ecc80a5111d2baaeab237b84dd25d025d9c65eb64e3cf32c81db346"

      def install
        bin.install "gitea-mirror"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nexthink-oss/gitea-mirror/releases/download/v0.6.0/gitea-mirror_0.6.0_darwin_arm64.zip"
      sha256 "3328489f6fb2a25956faaedb4c915d6998969c6030217dcdf84a323b575c5bbb"

      def install
        bin.install "gitea-mirror"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/gitea-mirror/releases/download/v0.6.0/gitea-mirror_0.6.0_linux_amd64.zip"
      sha256 "0b1dbd365d553b0e7c2e057c35bbe6d5b91d4ef6b159c119dd115d8ed1443ce2"
      def install
        bin.install "gitea-mirror"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nexthink-oss/gitea-mirror/releases/download/v0.6.0/gitea-mirror_0.6.0_linux_arm64.zip"
      sha256 "c1a0bf1b7ab4dc5eaca9199ffa99436d31bab794e8950c500902e20324ab282a"
      def install
        bin.install "gitea-mirror"
      end
    end
  end

  test do
    system "#{bin}/gitea-mirror --help"
  end
end
