# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoDigicertMpki < Formula
  desc "Go module and CLI for the DigiCert MPKI API"
  homepage "https://github.com/isometry/go-digicert-mpki/"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/go-digicert-mpki/releases/download/v0.0.6/go-digicert-mpki_0.0.6_darwin_amd64.zip"
      sha256 "df3eb6f0f8723e2c458bbaa0962d3803e46dc58df36ea3422391bd5eb0df50df"

      def install
        bin.install "digicert-mpki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/go-digicert-mpki/releases/download/v0.0.6/go-digicert-mpki_0.0.6_darwin_arm64.zip"
      sha256 "9c3a5a5abeb888cdce3d764922b5075675da90011f58fd0f2b359638e68d2937"

      def install
        bin.install "digicert-mpki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/go-digicert-mpki/releases/download/v0.0.6/go-digicert-mpki_0.0.6_linux_amd64.zip"
      sha256 "c9706096da1813dde8d73a0a82ce0352e6f13d6b297ac4c1a1f197c7b57b41fe"

      def install
        bin.install "digicert-mpki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/go-digicert-mpki/releases/download/v0.0.6/go-digicert-mpki_0.0.6_linux_arm64.zip"
      sha256 "01183d33b2513c68593c79f92d5e311de376b6a79cb1fd029e839d2c111adc79"

      def install
        bin.install "digicert-mpki"
      end
    end
  end
end
