# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformHealth < Formula
  desc "Platform health monitoring system"
  homepage "https://just.breathe.io/project/platform-health/"
  version "0.5.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/platform-health/releases/download/v0.5.6/platform-health_0.5.6_darwin_amd64.zip"
      sha256 "0af8a3a911ccf16d6946ae988bc1190be559f3acaee617c0975f5449fc1fae7f"

      def install
        bin.install "phc"
        bin.install "phs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/platform-health/releases/download/v0.5.6/platform-health_0.5.6_darwin_arm64.zip"
      sha256 "c7101e1d42efd735eca1c55fe40fd80dbfb4638e5471f8db6ee1a357d09477ba"

      def install
        bin.install "phc"
        bin.install "phs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/platform-health/releases/download/v0.5.6/platform-health_0.5.6_linux_amd64.zip"
        sha256 "f34ba9c077570995979e58f64f9ca49f874d0d8c923c6f0b9168350aafd3db1c"

        def install
          bin.install "phc"
          bin.install "phs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/platform-health/releases/download/v0.5.6/platform-health_0.5.6_linux_arm64.zip"
        sha256 "e368d98d490de1b458a59a08b85a013412f21e0806f17e04f2abba292671199a"

        def install
          bin.install "phc"
          bin.install "phs"
        end
      end
    end
  end
end
