# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformHealth < Formula
  desc "Platform health monitoring system"
  homepage "https://just.breathe.io/project/platform-health/"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/platform-health/releases/download/v0.4.1/platform-health_0.4.1_darwin_amd64.zip"
      sha256 "c6bf530b17eac1f0a8d57d79903d69e35f87a36bf1b60aaf4816540b5af5d7ff"

      def install
        bin.install "phc"
        bin.install "phs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/platform-health/releases/download/v0.4.1/platform-health_0.4.1_darwin_arm64.zip"
      sha256 "2d2d894b79c269197e5c0b138efe27d5cf7e004d33978ef7e6a03d3dd706a63c"

      def install
        bin.install "phc"
        bin.install "phs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/platform-health/releases/download/v0.4.1/platform-health_0.4.1_linux_amd64.zip"
      sha256 "0fa0217c5ced87efc362eed4b9b8c5538cd76877ec0fd52ad99b0aa71e922b19"

      def install
        bin.install "phc"
        bin.install "phs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/platform-health/releases/download/v0.4.1/platform-health_0.4.1_linux_arm64.zip"
      sha256 "5b4208214de16ad72bf4bb31df4a7091293df3d0d98fc67c6e5afa99c1b4313f"

      def install
        bin.install "phc"
        bin.install "phs"
      end
    end
  end
end
