# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultSshPlus < Formula
  desc "Automatically use HashiCorp Vault SSH Client Key Signing with ssh(1)"
  homepage "https://just.breathe.io/project/vault-ssh-plus/"
  version "0.7.7"

  depends_on "hashicorp/tap/vault" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.7/vault-ssh-plus_0.7.7_darwin_amd64.zip"
      sha256 "6ca291873e0041ee8fab3345846d8d9db6e1e74584cdead5183361fb5081206c"

      def install
        bin.install "vssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.7/vault-ssh-plus_0.7.7_darwin_arm64.zip"
      sha256 "4ff6b7a7d32c9260730f6d7ac8edfc2f124151f9ccbcb5658604926b0dd190ed"

      def install
        bin.install "vssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.7/vault-ssh-plus_0.7.7_linux_amd64.zip"
        sha256 "223eb75a3c5d928d4c7527342ec466ff48b2923d78ab18050468e4893d3e75f5"

        def install
          bin.install "vssh"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.7/vault-ssh-plus_0.7.7_linux_arm.zip"
        sha256 "0a5c8dd312fb5fca94752308cdaec0823908326d1c3f9542c49260bb87f0d270"

        def install
          bin.install "vssh"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.7/vault-ssh-plus_0.7.7_linux_arm64.zip"
        sha256 "f899bc8cc55b45b9cd8709f8a999d6ff29c08c62f826c858265971a6128d1992"

        def install
          bin.install "vssh"
        end
      end
    end
  end

  def caveats
    <<~EOS
      vssh requires the vault binary to be in your PATH.
      You can install it with:
        brew install hashicorp/tap/vault
    EOS
  end

  test do
    system "#{bin}/vssh --version"
  end
end
