# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultSshPlus < Formula
  desc "Automatically use HashiCorp Vault SSH Client Key Signing with ssh(1)"
  homepage "https://just.breathe.io/project/vault-ssh-plus/"
  version "0.7.5"

  depends_on "vault"

  on_macos do
    on_intel do
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.5/vault-ssh-plus_0.7.5_darwin_amd64.zip"
      sha256 "6c3d561ffc08512fe440a828a655f9d7910cab8636ca82c62c18b96f5642629d"

      def install
        bin.install "vssh"
      end
    end
    on_arm do
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.5/vault-ssh-plus_0.7.5_darwin_arm64.zip"
      sha256 "10ae4067cd62bffedb1358bb4ce616783a7355a53636919201aa03ceb09c288c"

      def install
        bin.install "vssh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.5/vault-ssh-plus_0.7.5_linux_amd64.zip"
        sha256 "57351d612b5bced6bf2b58f619ceab16a4bb62c3007e94e5a6351fddaa408d02"

        def install
          bin.install "vssh"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.5/vault-ssh-plus_0.7.5_linux_arm.zip"
        sha256 "df8af45a7a6d597b51628e044074309c7761de915eed30f2bab8c05acde30879"

        def install
          bin.install "vssh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.7.5/vault-ssh-plus_0.7.5_linux_arm64.zip"
        sha256 "6b399fd5c48e4d0b5c6626d5ccb7747deb57f0efca9265631e16c4c6a9d9e243"

        def install
          bin.install "vssh"
        end
      end
    end
  end

  test do
    system "#{bin}/vssh --version"
  end
end
