# This file was generated by GoReleaser. DO NOT EDIT.
class VaultSshClient < Formula
  desc "Automatically use HashiCorp Vault SSH Client Key Signing with ssh(1)"
  homepage "https://just.breathe.io/project/vault-ssh-client/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/isometry/vault-ssh-client/releases/download/v0.1.0/vault-ssh-client_0.1.0_darwin_amd64.zip"
    sha256 "a61022fb8e45e4911e1ad3661c960d4ef91cd6c0f9b16e6ca4a44154c115ce70"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/isometry/vault-ssh-client/releases/download/v0.1.0/vault-ssh-client_0.1.0_linux_amd64.zip"
      sha256 "5c021f67e7e47f82a0473b016542ce9db7a340a90f21dc2db59e73012b475c34"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/isometry/vault-ssh-client/releases/download/v0.1.0/vault-ssh-client_0.1.0_linux_arm64.zip"
        sha256 "ea2a063764002d3925ff2db3e2267135b05b9d48a592b2435476ff140dee3407"
      else
        url "https://github.com/isometry/vault-ssh-client/releases/download/v0.1.0/vault-ssh-client_0.1.0_linux_arm.zip"
        sha256 "3ec585f987f608d283a020b7c3d08db9a898b5f3a61473e0c3d1a9e7d38f96fa"
      end
    end
  end
  
  depends_on "vault"

  def install
    bin.install "vssh"
  end
end
