# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultSshPlus < Formula
  desc "Automatically use HashiCorp Vault SSH Client Key Signing with ssh(1)"
  homepage "https://just.breathe.io/project/vault-ssh-plus/"
  version "0.5.1"

  depends_on "vault"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.5.1/vault-ssh-plus_0.5.1_darwin_arm64.zip"
      sha256 "fb16e2cde09cc2b164b233d3a2acff4212256c50c3626e31aae5c1aab1b0fded"

      def install
        bin.install "vssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.5.1/vault-ssh-plus_0.5.1_darwin_amd64.zip"
      sha256 "4b8fa4a9cbd40c47746e235e611473b737e391121b2fb219a745d101c11eb8bb"

      def install
        bin.install "vssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.5.1/vault-ssh-plus_0.5.1_linux_arm.zip"
      sha256 "5ef81afdc7f78f71f993284287d21303ad221762fa8bcd0064a1f287d0c7c538"

      def install
        bin.install "vssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.5.1/vault-ssh-plus_0.5.1_linux_amd64.zip"
      sha256 "7c7e1f25d4e4c508cf52033627950f616bcedec6078c1deadd9441c90bd040ff"

      def install
        bin.install "vssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isometry/vault-ssh-plus/releases/download/v0.5.1/vault-ssh-plus_0.5.1_linux_arm64.zip"
      sha256 "8cf53b5ab64b8952c2cc1d17b7a9a97805df8d62a5c7ae361744eba71238baa5"

      def install
        bin.install "vssh"
      end
    end
  end

  test do
    system "#{bin}/vssh --version"
  end
end
